apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: identity-ingress
  namespace: circle-guard-master
  labels:
    app: circle-guard-identity
    project: circle-guard
    environment: master
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - circle-guard-identity.circleguard.edu
      secretName: circle-guard-identity-tls
  rules:
    - host: circle-guard-identity.circleguard.edu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: identity-service
                port:
                  number: 8080
