apiVersion: v1
kind: ConfigMap
metadata:
  name: circle-guard-config
  namespace: circle-guard-stage
data:
  SPRING_PROFILES_ACTIVE: "stage"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_NEO4J_URI: "bolt://neo4j:7687"
  SPRING_NEO4J_AUTHENTICATION_USERNAME: "neo4j"
  SPRING_LDAP_URLS: "ldap://openldap:389"
  SPRING_LDAP_BASE: "dc=circleguard,dc=edu"
  SPRING_LDAP_USERNAME: "cn=admin,dc=circleguard,dc=edu"
  AUTH_API_URL: "http://auth-service:8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
