apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: form-ingress
  namespace: circle-guard-stage
  labels:
    app: circle-guard-form
    project: circle-guard
    environment: stage
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: circle-guard-form.stage.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: form-service
                port:
                  number: 8080
