apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: circle-guard-dev
  labels:
    app: circle-guard-identity
    project: circle-guard
spec:
  type: ClusterIP
  selector:
    app: circle-guard-identity
  ports:
    - name: http
      port: 8080
      targetPort: 8083
