apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: circle-guard-dev
  labels:
    app: neo4j
    project: circle-guard
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:5.26
          ports:
            - name: http
              containerPort: 7474
            - name: bolt
              containerPort: 7687
          env:
            - name: NEO4J_AUTH
              value: "neo4j/password"
            - name: NEO4J_PLUGINS
              value: '["apoc"]'
            - name: NEO4J_dbms_connector_bolt_listen__address
              value: ":7687"
            - name: NEO4J_dbms_connector_bolt_advertised__address
              value: ":7687"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 7474
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: neo4j-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
