apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap
  namespace: circle-guard-dev
  labels:
    app: openldap
    project: circle-guard
spec:
  serviceName: openldap
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          ports:
            - name: ldap
              containerPort: 389
            - name: ldaps
              containerPort: 636
          env:
            - name: LDAP_ORGANISATION
              value: "CircleGuard"
            - name: LDAP_DOMAIN
              value: "circleguard.edu"
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: circle-guard-secrets
                  key: LDAP_ADMIN_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            exec:
              command:
                - "ldapsearch"
                - "-x"
                - "-H"
                - "ldap://localhost"
                - "-b"
                - ""
                - "-s"
                - "base"
                - "(objectclass=*)"
                - "namingContexts"
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
          volumeMounts:
            - name: ldap-data
              mountPath: /var/lib/ldap
            - name: ldap-config
              mountPath: /etc/ldap/slapd.d
  volumeClaimTemplates:
    - metadata:
        name: ldap-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: ldap-config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
